-- Apply only to the NEW Supabase project. Never to the legacy database.
begin;
create table public.about (
  id bigint generated by default as identity primary key,
  paragraph_1 text not null, paragraph_2 text not null, paragraph_3 text not null,
  updated_at timestamp not null
);
create table public.music (
  id bigint generated by default as identity primary key,
  title varchar(180) not null, artists varchar(220) not null,
  youtube_url varchar(500) not null, youtube_video_id varchar(30) not null,
  position integer not null, created_at timestamp not null
);
create index music_position_idx on public.music(position, id);
create table public.events (
  id bigint generated by default as identity primary key,
  title varchar(255), event_date date, city varchar(255), location varchar(255),
  description varchar(1000), ticket_url varchar(255)
);
create table public.admin_users (
  id bigint generated by default as identity primary key,
  username varchar(100) not null unique, password varchar(100) not null,
  created_at timestamp not null, updated_at timestamp not null
);
create table public.admin_sessions (
  token_hash text primary key,
  admin_id bigint not null references public.admin_users(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index admin_sessions_user_idx on public.admin_sessions(admin_id);
create table public.login_attempts (
  key_hash text primary key, attempts integer not null,
  window_start timestamptz not null default now()
);

alter table public.about enable row level security;
alter table public.music enable row level security;
alter table public.events enable row level security;
alter table public.admin_users enable row level security;
alter table public.admin_sessions enable row level security;
alter table public.login_attempts enable row level security;

revoke all on public.about, public.music, public.events, public.admin_users,
  public.admin_sessions, public.login_attempts from anon, authenticated;
grant select on public.about, public.events to anon, authenticated;
create policy about_public_read on public.about for select to anon, authenticated using (true);
create policy events_public_read on public.events for select to anon, authenticated using (true);
-- The public projection exposes exactly the featured six, not the private archive.
create view public.featured_music as
  select id,title,artists,youtube_url,youtube_video_id,position,created_at
  from public.music order by position, id limit 6;
revoke all on public.featured_music from public;
grant select on public.featured_music to anon, authenticated, service_role;
-- Deliberate owner view: only the bounded projection is public. Base table has no public grant/policy.
grant all on public.about, public.music, public.events, public.admin_users,
  public.admin_sessions, public.login_attempts to service_role;
grant usage, select on sequence public.about_id_seq, public.music_id_seq,
  public.events_id_seq, public.admin_users_id_seq to service_role;

create function public.add_music(p_title text, p_artists text, p_url text, p_video_id text)
returns bigint language plpgsql security invoker set search_path = '' as $$
declare new_id bigint;
begin
  perform pg_advisory_xact_lock(61420260904);
  update public.music set position = position + 1 where id is not null;
  insert into public.music(title, artists, youtube_url, youtube_video_id, position, created_at)
    values (trim(p_title), trim(p_artists), trim(p_url), p_video_id, 1, localtimestamp)
    returning id into new_id;
  return new_id;
end;
$$;
create function public.delete_music(p_id bigint)
returns void language plpgsql security invoker set search_path = '' as $$
begin
  perform pg_advisory_xact_lock(61420260904);
  delete from public.music where id = p_id;
  if not found then raise exception 'Música não encontrada.'; end if;
  with positions as (select id, row_number() over(order by position, id) as pos from public.music)
  update public.music m set position = p.pos from positions p where m.id = p.id;
end;
$$;
create function public.save_about(p_1 text, p_2 text, p_3 text)
returns void language plpgsql security invoker set search_path = '' as $$
declare first_id bigint;
begin
  perform pg_advisory_xact_lock(61420260905);
  select id into first_id from public.about order by id limit 1;
  if first_id is null then
    insert into public.about(paragraph_1,paragraph_2,paragraph_3,updated_at)
      values(p_1,p_2,p_3,localtimestamp);
  else
    update public.about set paragraph_1=p_1,paragraph_2=p_2,paragraph_3=p_3,
      updated_at=localtimestamp where id=first_id;
  end if;
end;
$$;
create function public.consume_login_attempt(p_key text)
returns boolean language plpgsql security invoker set search_path = '' as $$
declare n integer;
begin
  delete from public.login_attempts where window_start < now() - interval '1 day';
  insert into public.login_attempts(key_hash, attempts) values(p_key, 1)
  on conflict(key_hash) do update set
    attempts = case when public.login_attempts.window_start < now() - interval '15 minutes'
      then 1 else public.login_attempts.attempts + 1 end,
    window_start = case when public.login_attempts.window_start < now() - interval '15 minutes'
      then now() else public.login_attempts.window_start end
  returning attempts into n;
  return n <= 10;
end;
$$;
create function public.change_admin_password(p_id bigint, p_old_hash text, p_new_hash text)
returns boolean language plpgsql security invoker set search_path = '' as $$
begin
  update public.admin_users set password=p_new_hash, updated_at=localtimestamp
    where id=p_id and password=p_old_hash;
  if not found then return false; end if;
  delete from public.admin_sessions where admin_id=p_id;
  return true;
end;
$$;
revoke all on function public.add_music(text,text,text,text), public.delete_music(bigint),
  public.save_about(text,text,text), public.consume_login_attempt(text),
  public.change_admin_password(bigint,text,text) from public, anon, authenticated;
grant execute on function public.add_music(text,text,text,text), public.delete_music(bigint),
  public.save_about(text,text,text), public.consume_login_attempt(text),
  public.change_admin_password(bigint,text,text) to service_role;
commit;
